spring:
  config:
    import: file:./.env[.properties]
  application:
    name: ARGOS Homeless
  sql:
    init:
      encoding: UTF-8
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        validator:
          apply_to_ddl: true

springdoc:
  api-docs:
    path: "/api-docs"