spring:
  config:
    import: file:./.env[.properties]
  application:
    name: ARGOS Homeless
  sql:
    init:
      encoding: UTF-8
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        validator:
          apply_to_ddl: true

security:
  jwt:
    token:
      expire-length: 300000

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
